### ISSUE TITLE
setup and test zeppelin for analysis

### ISSUE THREAD

**Issue by cfregly** [bythebay/pipeline#6]

**Comment by cfregly** [comment]
@swartzrock :  we'll need port 7070 exposed on either the master or slave.

we'll also need to build from the source at https://github.com/apache/incubator-zeppelin.git.  This requires a higher version of maven then is available from default package managers, so this is a bit tricky.  

here's how we'd do this http://linuxg.net/how-to-install-apache-maven-3-2-1-on-ubuntu-14-04-linux-mint-17-and-their-derivative-systems/

@swartzrock is suggesting to pre-build it, then add it to the git repo.

**Comment by andypetrella** [comment]
Hey guyz,
Dunno what's the plan with Zeppelin but the training website announces the
spark notebook for this analysis phase.
Maybe the pipeline can integrate it later, nor that the spark notebook is
fully Scala (for a Scala conference, I guess it has its importance) and a
lot of companies are these days coming to me because they swap from
Zeppelin to spark notebook (apparently for stability reasons).

Also the spark notebook has a bunch of pre-built versions, and there is
even a website to generate new ones if necessary 😊.

The point is, let's be fair, I'm coming from Belgium (and quitting my 3
months old baby) quite some days earlier for the pipeline training. You
wouldn't like adding something about Flink in this situation right 😅.

Andy

Le sam. 11 juil. 2015 02:16, Chris Fregly notifications@github.com a
écrit :

**Comment by cfregly** [comment]
done
